# permissions for end users to view autoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-auto-scaler
    app.kubernetes.io/managed-by: kustomize
  name: autoscaler-viewer-role
rules:
- apiGroups:
  - scaling.example.com
  resources:
  - autoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.example.com
  resources:
  - autoscalers/status
  verbs:
  - get
