apiVersion: scaling.example.com/v1
kind: AutoScaler
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-auto-scaler
    app.kubernetes.io/managed-by: kustomize
  name: autoscaler-sample
spec:
  # TODO(user): Add fields here
